export const SET_USER_INPUT = 'SET_USER_INPUT';
export const TOGGLE_SHOW_PASSWORD = 'TOGGLE_SHOW_PASSWORD';
export const SET_VALIDATION_MESSAGE = 'SET_VALIDATION_MESSAGE';
export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const INIT_GET_PROFILE = 'INIT_GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';


export const CHANGE_COMPOSE_EMAIL_USER_INPUT = 'CHANGE_COMPOSE_EMAIL_USER_INPUT';
export const RESET_COMPOSE_EMAIL_USER_INPUTS = 'RESET_COMPOSE_EMAIL_USER_INPUTS';
export const INIT_SEND_EMAIL = 'INIT_SEND_EMAIL';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';
export const UPDATE_SENT_EMAIL_LIST = 'UPDATE_SENT_EMAIL_LIST';


export const INIT_GET_EMAILS = 'INIT_GET_EMAILS';
export const GET_EMAILS_SUCCESS = 'GET_EMAILS_SUCCESS';
export const GET_EMAILS_FAIL = 'GET_EMAILS_FAIL';
export const SELECT_EMAIL = 'SELECT_EMAIL';
export const UNSELECT_EMAIL = 'UNSELECT_EMAIL';
export const UNSELECT_ALL_EMAILS = 'UNSELECT_ALL_EMAILS';
export const INIT_DELETE_EMAIL = 'INIT_DELETE_EMAIL';
export const DELETE_EMAIL_SUCCESS = 'DELETE_EMAIL_SUCCESS';
export const DELETE_EMAIL_FAIL = 'DELETE_EMAIL_FAIL';